version: '2'
services:
    auth:
        build:
            context: .
            dockerfile: auth/Dockerfile
        restart: always
        volumes:
            - .:/go/src/scm
        container_name: auth
        ports:
            - 8802:8082
    db:
        build:
            context: .
            dockerfile: db/Dockerfile
        container_name: db
        ports:
            - 8800:8081
        restart: always
        volumes:
            - .:/go/src/scm
    osm:
        build:
            context: .
            dockerfile: osm/Dockerfile
        restart: always
        volumes:
            - .:/go/src/scm
        container_name: osm
        ports:
            - 8801:8081
    ui:
        build:
            context: .
            dockerfile: ui/Dockerfile
        restart: always
        volumes:
            - .:/go/src/scm
        container_name: ui
        ports:
            - 8803:8081
    etcd:
        image: 'quay.io/coreos/etcd:v3.1.7'
        restart: always
        ports:
            - '23791:2379'
            - '23801:2380'
        environment:
            ETCD_NAME: infra
            ETCD_INITIAL_ADVERTISE_PEER_URLS: 'http://etcd:2380'
            ETCD_INITIAL_CLUSTER: infra=http://etcd:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: secrettoken
            ETCD_LISTEN_CLIENT_URLS: 'http://etcd:2379,http://localhost:2379'
            ETCD_LISTEN_PEER_URLS: 'http://etcd:2380'
            ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd:2379'
